"""Added users account auto

Revision ID: 07c19438ca9a
Revises: 49922e64d04f
Create Date: 2023-04-21 17:51:01.324058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07c19438ca9a'
down_revision = '49922e64d04f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
