"""change the name of a column

Revision ID: 6fbfb053419d
Revises: 4ee0e0169d8b
Create Date: 2023-04-23 13:58:21.440456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fbfb053419d'
down_revision = '4ee0e0169d8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('address', sa.String(length=100), nullable=False))
    op.add_column('client', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('client', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_foreign_key(None, 'client', 'user', ['user_id'], ['id'])
    op.drop_column('client', 'adress')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('adress', sa.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.alter_column('client', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('client', 'user_id')
    op.drop_column('client', 'address')
    # ### end Alembic commands ###
